apiVersion: v1
kind: Service
metadata:
  name: pet
spec:
  type: NodePort
  selector:
    app: pet
  ports:
      - name: http
        port: 8080
        targetPort: 8080
        protocol: TCP
        nodePort: 30001
